config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'

  devise_for :users
  authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  unauthenticated do
    root 'categories#splash', as: :unauthenticated_root
  end

  resources :categories, only: %i[index new  create destroy] do
    resources :expenses, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses
  validates :name, :icon, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expenses
  has_many :categories, through: :category_expenses

  validates :amount, numericality: { greater_than: 0 }
  validates :name, presence: true

  validates :category_ids, presence: { message: 'must be selected' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, presence: true, allow_blank: false, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:splash]

  ICON_OPTIONS = ['🍔', '🛒', '🚗', '🐶', '📚', '💻', '🎁', '🏠', '🏥', '🎬', '👔', '🎓'].freeze

  def index
    @categories = current_user.categories.includes(:expenses)
  end

  def new
    @category = Category.new
    @options = ICON_OPTIONS
  end

  def create
    icon = categories_params[:icon].presence || ICON_OPTIONS.first

    @category = current_user.categories.build(categories_params.merge(icon:))

    if @category.save
      redirect_to categories_path, notice: 'Expense category was successfully created.'
    else
      flash.now[:alert] = 'Try again. Cannot create a new expense category.'
      render :new
    end
  end

  def splash; end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to categories_path, alert: 'Expense category deleted successfully.'
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon).merge(user_id: current_user.id)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @expense = @category.expenses.build(category_ids: [@category.id])
    @categories = Category.all
  end

  def create
    @category = Category.find_by(id: params[:category_id])

    if @category.nil?
      redirect_to root_path, alert: 'Category not found'
      return
    end

    @categories = Category.all

    if @categories.empty?
      redirect_to root_path, alert: 'No categories available'
      return
    end

    @expense = @category.expenses.build(expense_params)

    if @expense.save
      redirect_to category_expenses_path(category_id: @category.id), notice: 'Expense was successfully created.'
    else
      flash.now[:alert] = 'Expense cannot be created.'
      render :new
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.categories.each do |category|
      category.category_expenses.find_by(expense_id: @expense.id).destroy
    end

    @expense.destroy
    redirect_to category_expenses_path(category_id: params[:category_id]), alert: 'Expense deleted successfully.'
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: []).merge(author_id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def sign_out_user
    sign_out(current_user)
    redirect_to authenticated_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/confirmations_helper.rb
module Users::ConfirmationsHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users/unlocks_helper.rb
module Users::UnlocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/9e6b5903a6.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

    <!-- Add Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_head.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <% if back %>
      <%= link_to("javascript:history.back()", class: "navbar-text text-white text-2xl") do %>
        <i class="fas fa-angle-left text-2xl text-white"></i>
      <% end %>
    <% else %>
      <i class="fa-solid fa-bars text-2xl text-white"></i>
    <% end %>

    <h2 class="navbar-text text-2xl font-semibold text-white text-uppercase"><%= title %></h2>

    <% if title == "categories" || title == "Expenses" %>
      <%= link_to sign_out_user_path, class: "navbar-text text-white text-2xl" do %>
        <i class="fa-solid fa-arrow-right-from-bracket" style="color: #fcfcfc;"></i>
      <% end %>
    <% elsif title == "register" %>
      <%= link_to new_user_session_path, class: "navbar-text text-white text-2xl" do %>
        <span class="font-normal">Next</span>
      <% end %>
    <% elsif title == "login" %>
      <%= link_to new_user_registration_path, class: "navbar-text text-white text-2xl" do %>
        <span class="fas fa-user-plus"></span>
      <% end %>
    <% else %>
      <%= link_to sign_out_user_path, class: "navbar-text text-white text-2xl" do %>
        <i class="fa-solid fa-arrow-right-from-bracket" style="color: #fcfcfc;"></i>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/shared/_message.html.erb
<div class=" message-container">
        <div class="<%= status %> flex justify-content-between" id="alert-box">
          <% if status == 'notice' %>
            <span class=""><%= notice %></span>
          <% else %>
                <span class=""><%= alert %></span>
            <% end %>
            <button type="button" class="btn-close"  onclick='closeMessage()' aria-label="Close"></button>
        </div>

</div>

<script>

    function closeMessage() {
        document.getElementById('alert-box').style.display = "none"
    }
</script>