config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'

  devise_for :users
  authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  unauthenticated do
    root 'categories#splash', as: :unauthenticated_root
  end

  resources :categories, only: %i[index new  create destroy] do
    resources :expenses, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses
  validates :name, :icon, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expenses
  has_many :categories, through: :category_expenses

  validates :amount, numericality: { greater_than: 0 }
  validates :name, presence: true

  validates :category_ids, presence: { message: 'must be selected' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, presence: true, allow_blank: false, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:splash]

  ICON_OPTIONS = ['🍔', '🛒', '🚗', '🐶', '📚', '💻', '🎁', '🏠', '🏥', '🎬', '👔', '🎓'].freeze

  def index
    @categories = current_user.categories.includes(:expenses)
  end

  def new
    @category = Category.new
    @options = ICON_OPTIONS
  end

  def create
    icon = categories_params[:icon].presence || ICON_OPTIONS.first

    @category = current_user.categories.build(categories_params.merge(icon:))

    if @category.save
      redirect_to categories_path, notice: 'Expense category was successfully created.'
    else
      flash.now[:alert] = 'Try again. Cannot create a new expense category.'
      render :new
    end
  end

  def splash; end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to categories_path, alert: 'Expense category deleted successfully.'
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon).merge(user_id: current_user.id)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @expense = @category.expenses.build(category_ids: [@category.id])
    @categories = Category.all
  end

  def create
    @category = Category.find_by(id: params[:category_id])

    if @category.nil?
      redirect_to root_path, alert: 'Category not found'
      return
    end

    @categories = Category.all

    if @categories.empty?
      redirect_to root_path, alert: 'No categories available'
      return
    end

    @expense = @category.expenses.build(expense_params)

    if @expense.save
      redirect_to category_expenses_path(category_id: @category.id), notice: 'Expense was successfully created.'
    else
      flash.now[:alert] = 'Expense cannot be created.'
      render :new
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.categories.each do |category|
      category.category_expenses.find_by(expense_id: @expense.id).destroy
    end

    @expense.destroy
    redirect_to category_expenses_path(category_id: params[:category_id]), alert: 'Expense deleted successfully.'
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: []).merge(author_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def sign_out_user
    sign_out(current_user)
    redirect_to authenticated_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/confirmations_helper.rb
module Users::ConfirmationsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users/unlocks_helper.rb
module Users::UnlocksHelper
end

app/views/categories/index.html.erb
<section class="category-section">
  <div class="category-container">
    <%= render "shared/head", title: 'categories', back: false %>
    <div class="success-fail">
      <% if flash[:notice] %>
        <%= render 'shared/message', message: flash[:notice], status: 'success' %>
      <% end %>

      <% if flash[:alert] %>
        <%= render 'shared/message', message: flash[:alert], status: 'danger' %>
      <% end %>
    </div>

    <% if @categories.empty? %>
      <div class="w-100  d-flex justify-content-center align-items-center">
        <div class="getting-started-container w-100 p-3 p-md-5">
          <h2 class="text-center">Getting Started?</h2>
          <div class="introduction my-3 my-md-5">
            <p>A mobile web application where you can manage your budget: you have a list of transactions associated with a category,
              so that you can see how much money you spent and on what.</p>
          </div>
          <div class="for-category my-3 my-md-5">
            <h2>Category</h2>
            <p>
              For each category, the user can see their name, icon and the total amount of all the transactions that belong to that category.
              When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
              There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
            </p>
          </div>
          <div class="for-expense my-3 my-md-5">
            <h2>Expense</h2>
            <p>
              Here, you can view and manage transactions in a specific category. The total category amount is displayed at the top. To add a new transaction, scroll down and click "Add a New Transaction." Use the "<" button to return to the home page. Enjoy!
            </p>
          </div>
        </div>
      </div>
    <% else %>
      <ul class="list-group mt-5 category-container bg-light">
        <% @categories.each do |category| %>
          <%= link_to category_expenses_path(category_id: category.id), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center mb-3' do %>
            <div class="text-4xl me-2 me-md-4"><%= category.icon %></div>
            <div class="text-lg font-weight-bold"><%= category.name %></div>
            <div class="text-lg font-weight-bold">$<%= format('%.2f', category.expenses.sum(:amount)) %></div>
          <% end %>
        <% end %>
      </ul>
    <% end %>
<div class="mt-auto">
      <div class="add-category-container d-flex justify-content-center px-3 px-md-5 py-3">
        <%= link_to "ADD CATEGORY", new_category_path, class: 'btn btn-outline-light btn-lg' %>
      </div>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<section class="category-section">
    <div>
        <%= render "shared/head", title: "add category", back: true %>
    </div>
    <% if flash[:notice].present? %>
        <div class="notice">
            <%= flash[:notice] %>
        </div>
    <% end %>

    <div class="form-container">
        <%= form_with model: @category do |form| %>
            <div class="border p-3 p-md-5">
                <%= form.text_field :name, required: true, placeholder: "Enter New Category", class: 'form-control' %>
                <%= form.select :icon, options_for_select(@options, selected: @category.icon), { prompt: "Select an icon" }, class: 'form-select mb-3' %>
            </div>

            <div class="add-category-container d-flex justify-content-center px-3 px-md-5 py-3 py-md-5">
                <%= form.submit "Create category", class: 'btn btn-primary btn-lg w-80' %>
            </div>
        <% end %>
    </div>
</section>

app/views/categories/show.html.erb
<% if can? :read, @category %>
<div class="container mt-0">
<div class="d-flex justify-content-between bg-primary text-light align-items-center">
<%= link_to categories_path do %>
  <i class="bx bxs-chevron-left display-4 text-white"></i>
<% end %>
  <h3 class="card-title"><%= @category.name %></h3>
  <h3 class="card-subtitle">$<%= @total %></h3>
</div>

  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div class="card">
        <div class="card-body">
          <div class="mt-4 purchases">
            <% @category.purchases.reverse.each do |p| %>
              <div class="card mb-2">
                <div class="card-body">
                  <p class="card-text"><%= p.name %> - <%= p.created_at.strftime("%d %B %Y")%></p>
                  <p class="card-text">$<%= p.amount %></p>
                </div>
              </div>
            <% end %>
          </div>
          <div class="text-center mt-4">
            <%= link_to 'Add Transaction', new_category_purchase_path(@category), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
<h1>You are not authorized to view this page</h1>
<% end %>

app/views/categories/splash.html.erb
<section class="splash-section d-flex flex-column align-items-center justify-content-center vh-100 text-center">
    <div class="title-container mt-auto">
        <h2 class="fst-italic text-3xl splash-title">Budget</h2>
    </div>
    <div class="d-flex flex-column w-100 mt-auto">
        <%= link_to "LOG IN", new_user_session_path, class: 'btn custom btn-primary btn-lg m-2' %>
        <%= link_to "SIGN UP", new_user_registration_path, class: 'btn custom btn-outline-secondary btn-lg m-2' %>
    </div>
</section>