config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'

  devise_for :users
  authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  unauthenticated do
    root 'categories#splash', as: :unauthenticated_root
  end

  resources :categories, only: %i[index new  create destroy] do
    resources :expenses, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses
  validates :name, :icon, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expenses
  has_many :categories, through: :category_expenses

  validates :amount, numericality: { greater_than: 0 }
  validates :name, presence: true

  validates :category_ids, presence: { message: 'must be selected' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, presence: true, allow_blank: false, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:splash]

  ICON_OPTIONS = ['🍔', '🛒', '🚗', '🐶', '📚', '💻', '🎁', '🏠', '🏥', '🎬', '👔', '🎓'].freeze

  def index
    @categories = current_user.categories.includes(:expenses)
  end

  def new
    @category = Category.new
    @options = ICON_OPTIONS
  end

  def create
    icon = categories_params[:icon].presence || ICON_OPTIONS.first

    @category = current_user.categories.build(categories_params.merge(icon:))

    if @category.save
      redirect_to categories_path, notice: 'Expense category was successfully created.'
    else
      flash.now[:alert] = 'Try again. Cannot create a new expense category.'
      render :new
    end
  end

  def splash; end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to categories_path, alert: 'Expense category deleted successfully.'
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon).merge(user_id: current_user.id)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @expense = @category.expenses.build(category_ids: [@category.id])
    @categories = Category.all
  end

  def create
    @category = Category.find_by(id: params[:category_id])

    if @category.nil?
      redirect_to root_path, alert: 'Category not found'
      return
    end

    @categories = Category.all

    if @categories.empty?
      redirect_to root_path, alert: 'No categories available'
      return
    end

    @expense = @category.expenses.build(expense_params)

    if @expense.save
      redirect_to category_expenses_path(category_id: @category.id), notice: 'Expense was successfully created.'
    else
      flash.now[:alert] = 'Expense cannot be created.'
      render :new
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.categories.each do |category|
      category.category_expenses.find_by(expense_id: @expense.id).destroy
    end

    @expense.destroy
    redirect_to category_expenses_path(category_id: params[:category_id]), alert: 'Expense deleted successfully.'
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: []).merge(author_id: current_user.id)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def sign_out_user
    sign_out(current_user)
    redirect_to authenticated_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/confirmations_helper.rb
module Users::ConfirmationsHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users/unlocks_helper.rb
module Users::UnlocksHelper
end

app/views/expenses/index.html.erb
<div class="expen-container">
<%= render "shared/head", title: 'Expenses', back: true %>

<div class="alert-section">
  <% if flash[:notice] %>
    <%= render 'shared/message', message: flash[:notice], status: 'notice' %>
  <% end %>

  <% if flash[:alert] %>
    <%= render 'shared/message', message: flash[:alert], status: 'alert' %>
  <% end %>
</div>

  <div class="expense-container bg-light">
    <% if @expenses.empty? %>
      <div class="no-expense-container text-center">
        <h2 class="text-white border px-4 py-3 shadow-sm text-md font-semibold">There is no expense for this category</h2>
      </div>
    <% else %>
      <ul class="bg-light m-0 p-0 bg-light">
        <li class="category-list px-2 d-flex justify-content-between shadow-lg py-5 my-5 bg-white">
          <h2 class="font-semibold text-md text-black">Total Amount:</h2>
          <span class="font-semibold text-md">$<%= @total %></span>
        </li>
        <li class="category-list  mx-2 d-flex justify-content-between shadow-lg px-3 py-5 my-5 bg-white">
          <div class="icon-container text-3xl me-4"><%= @category.icon %></div>
          <div class="text-md opacity-75 font-semibold text-uppercase"><%= @category.name %></div>
          <%= button_to category_path(@category), method: :delete, class: 'btn' do %>
            <i class="fas fa-trash text-xl"></i>
          <% end %>
        </li>

        <% @expenses.each do |expense| %>
          <li class="card mx-2 mb-3">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                  <div class="icon-container text-3xl me-4"><%= @category.icon %></div>
                  <span class="text-uppercase text-muted font-semibold"><%= expense.name %></span>
                <span class="font-semibold text-md">$<%= format('%.2f', expense.amount) %></span>
              </div>
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center p-1">
              <span class="text-uppercase text-muted font-semibold"><%= expense.created_at.strftime('%d-%m-%Y') %></span>
              <%= button_to category_expense_path(@category, expense), method: :delete, class: 'btn' do %>
                <i class="fas fa-trash text-xl"></i>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
<div class="mt-auto">
  <div class="add-category-container mt- d-flex justify-content-center px-3 py-4">
    <%= link_to "ADD EXPENSE", new_category_expense_path(category_id: @category.id), class: 'btn btn-outline-light btn-lg text-white py-3' %>
  </div>
</div>
</div>

app/views/expenses/new.html.erb
<%= render 'shared/head', title: 'Add Expense', back: true %>

<section class="expense-section">
  <div class="expense-container"> 
    <% if flash[:notice].present? %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
        
    <div class="form-container">
      <%= form_with model: [@category, @expense], url: category_expenses_path(@category), method: :post do |form| %>
  <div class="border p-5 vh-80">
    <%= form.text_field :name, required: true, placeholder: "Enter New Expense", class: 'form-control mb-5' %>
    <%= form.number_field :amount, required: true, placeholder: "Amount (USD)", class: 'form-control' %>

    <div class="mb-3">
      <label class="form-label">Select Categories (at least one)</label>
      <%= form.collection_check_boxes :category_ids, @categories, :id, :name, checked: @expense.category_ids, class: 'form-check-input' do |cb| %>
        <%= cb.check_box %>
        <%= cb.label %>
      <% end %>
    </div>
  </div>

  <div class="add-category-container d-flex justify-content-center px-5 py-7">
    <%= form.submit "Create Expense", class: 'btn btn-outline-light my-2 btn-lg w-80 text-uppercase' %>
  </div>
<% end %>

    </div>
  </div>
</section>